services:
  api:
    container_name: "docker_api"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "7240:7240"
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: docker_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend
    command:
      - "postgres"
      - "-c"
      - "ssl=off" # Explicitly disable SSL

volumes:
  pgdata:
  pgadmin_data:

networks:
  backend:
    driver: bridge
